<?php
/*
 * This file is part of the NB Framework package.
 *
 * Copyright (c) 2018 https://nb.cx All rights reserved.
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */
return [
    'ddz_coin_10'=> [
        'name'=>'小包欢乐豆',
        'price'=>1.00,
        'coin'=>10
    ],
    'ddz_coin_100'=> [
        'name'=>'大包欢乐豆',
        'price'=>9.00,
        'coin'=>100
    ]
];